### ISSUE TITLE
Choose between /Dockerfile and /build/Dockerfile

### ISSUE THREAD

**Issue by axelmagn** [ksalama/ucaip-labs#1]
I think having more than one Dockerfile is probably unnecessary complexity at this point.

**Comment by ksalama** [comment]
I see. However, they serve two different purposes.
1. The one in the root define the runtime environment for the training pipeline tasks
2. The one under the `build` folder defines the runtime environment for the build steps

We can definitely have a single one in this example, but generally they should be separated
